##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.controlplane.base AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_NAME="modeco" \
    CONTECO_TAG="v1.0.3" \
    CONTECO_BASE="controlplane.base" \
    CONTECO_BUILD="image"
LABEL io.vcweb.name="modeco" \
      io.vcweb.tag="v1.0.3" \
      io.vcweb.base="controlplane.base" \
      io.vcweb.build="image" \
      io.vcweb.label="Conteco controlplane modeco" \
      io.vcweb.description="The Conteco controlplane modeco image." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.controlplane.modeco --help" 
##### END image/Dockerfile/env-labels-footer #####
