#!/usr/bin/env bash

export CONTECO_LABEL=" controlplane.modeco - Conteco"
export CONTECO_DESCRIPTION="The Conteco controlplane modeco image."

export CONTECO_TYPE="controlplane"
export CONTECO_NAME="modeco"
export CONTECO_TAG="v1.3.3"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="controlplane.base"
export CONTECO_BUILD="image"
