#!/usr/bin/env bash

export CONTECO_LABEL="Conteco controlplane modeco"
export CONTECO_DESCRIPTION="The Conteco controlplane modeco image."

export CONTECO_TYPE="controlplane"
export CONTECO_NAME="modeco"
export CONTECO_TAG="v1.1.0"

export CONTECO_BASE="controlplane.base"
export CONTECO_BUILD="image"
